version: '3.6'
services:
    node:
        image: 'node:latest'
        working_dir: /home/node/app
        command:
            - /bin/sh
            - '-c'
            - 'npm install && npm install --save-dev jest && npm start'
        ports:
            - '300:3000'
        volumes:
            - './:/home/node/app'